# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: hoowhoami.EchoMusic
PackageVersion: 2.3.1
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/hoowhoami/EchoMusic/releases/download/v2.3.1/EchoMusic-2.3.1-Windows-Setup-x64.exe
  InstallerSha256: 75E9BCBED2B34FE8F5A37F18FFF5E05551D4033AC102396C786CC86A04FDFE63
ManifestType: installer
ManifestVersion: 1.12.0
